### ISSUE TITLE
No module named "solver"

### ISSUE THREAD

**Issue by dhalpern1** [jsalvatier/scikits.bvp_solver#8]
Hi,
I followed the installation instructions and used easy_install on MACOS and also also on linux.
However, I get the following error on both machines by running one of the test programs (which I renamed test1.py):

Traceback (most recent call last):
  File "test1.py", line 1, in <module>
    import scikits.bvp_solver
  File "/usr/local/lib/python3.7/site-packages/scikits.bvp_solver-1.1-py3.7-macosx-10.13-x86_64.egg/scikits/bvp_solver/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'solver'

Any help would be appreciated.
Thanks.

David

**Comment by wingkitlee0** [comment]
have you tried the git version and use: `pip install -e .` or `python setup.py install` ?

if that does not work, you can try my fork repo: [https://github.com/wingkitlee0/scikits.bvp_solver/tree/master
](url) as I might have fixed a few things for python 3.

**Comment by dhalpern1** [comment]
I tried pip and setup.py, and both gave the same error messages. I will try your fork.
Thanks.

**Comment by wingkitlee0** [comment]
Feel free to post back your result. It will be helpful for others to know if it works or not. Thanks!

**Comment by Felimatus** [comment]
Hi there! I hav the same problem, I was trying to use py_bvp, which was unsuccessful. I received "ImportError: No module named bvp_solverf", so I installed  scikits.bvp_solver but eveytime I received the same message, ModuleNotFoundError: No module named 'solver'. Any help?

**Comment by wingkitlee0** [comment]
Hi, feel free to try my branch above.

**Comment by jsalvatier** [comment]
Yes, I think Kit's repo is the thing that's working right now. Kit and I
were going to arrange for him to take over the main repo, but haven't
gotten around to it yet.

**Comment by Felimatus** [comment]
Hi, thank you for your replies :D 
To be honest, I can check how it's working, I installed it using "python setup.py install" with the git version... and I still receive the same message....
